### PR TITLE
Added useful script for customizing/truncating output from cur_playing.

### PR DESCRIPTION
**Pull request by saevarb**
I'm not very fond of the `|` separator from `cur_playing`, and I prefer some ability to customize the order of the artist/song and even the output, including truncating it if songs have ridiculously long names.

I whipped this up for my own use with xmobar.

### CODE REVIEW

**Comment by SimonPersson** [comment]
The `|` separator was chosen to be easily parseable in scripts as very few songs or artists has it in their name. Any other separator would probably be used in a title somewhere and mess up parsing scripts. I obviously understand that not everyone finds it that pretty though :)

If you edit the `README.md` for the scripts dir with a short description of your script too I will merge this.

**Comment by saevarb** [comment]
Oh, sorry. I was in a hurry before leaving for home and forgot to edit the readme. 

I figured that was the reason you chose the separator -- it's a good idea, and while I dislike it visually, I like it for the reason you mentioned because I like easily parsable output.

**Comment by saevarb** [comment]
I have edited the readme. FYI, I'm the IceDane guy from reddit, and I'd prefer a link to my github instead of my reddit user, so I hope it's okay that I went ahead and changed that.

I also renamed the two scripts I have provided to something more sensible.

**Comment by SimonPersson** [comment]
Thank you. Merged.

**Pull request merged**
